services:
  file:
    build:
      context: ./backend/src/file_service
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    env_file:
      - ./backend/src/file_service/.env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - storage_data:/app/storage

  metadata:
    build:
      context: ./backend/src/metadata_service
      dockerfile: Dockerfile
    ports: 
      - 5001:5001
    env_file:
      - ./backend/src/metadata_service/.env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - storage_data:/app/storage
  database:
    image: postgres:17
    env_file:
      - .env
    ports:
      - 5433:5432 
    volumes:
      - postgre_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
volumes:
  postgre_data:
  storage_data: