name: CI

on: 
  push:
    paths:
      - "backend/**"
      - ".github/workflows/**"
      - "terraform/**"
  
  pull_request:
    paths:
      - "backend/**"

permissions:
  contents: read

jobs:       
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
            # usa caching de dependências para agilizar a execução do workflow
            cache: pip
            cache-dependency-path: backend/requirements.txt
  
        - name: Install dependencies
          # usar python garante que o pip pertence ao interpretador configurado 
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r backend/requirements.txt
    
        - name: Run ruff
          run: |
            ruff format --check backend/

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # usa caching de dependências para agilizar a execução do workflow
          cache: pip
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        # usar python garante que o pip pertence ao interpretador configurado 
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
  
      - name: Run Tests
        run: |
          cd backend/tests
          pytest -v

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Build lambda package
        run: |
          mkdir build
  
          pip install \
              --target build \
              -r backend/requirements.txt
  
          cp -r backend/src build/src
          cp backend/main.py build/
          cp backend/__init__.py build/

      - name: Create zip
        run: |
          cd build
          zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload artifact to S3
        run: |
          aws s3 cp \
            lambda.zip \
            s3://fileuploader-zip/lambda/${{ github.sha }}.zip
