name: File Service

on:
  push:
    paths:
      - "backend/src/file_service/**"

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    with:
      service-name: file-service
      service-path: backend/src/file_service
      lambda-name: file-service