name: Run Backend Tests

on: 
  push:
    paths:
      - "backend/**"
      - ".github/workflows/**"
  
  pull_request:
    paths:
      - "backend/**"

defaults:
  run:
    working-directory: backend



jobs:       
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
            # usa caching de dependências para agilizar a execução do workflow
            cache: pip
            cache-dependency-path: backend/requirements.txt
  
        - name: Install dependencies
          # usar python garante que o pip pertence ao interpretador configurado 
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
    
        - name: Run ruff
          run: |
            ruff format --check .
        - name: Run MyPy
          run: |
            mypy .

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # usa caching de dependências para agilizar a execução do workflow
          cache: pip
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        # usar python garante que o pip pertence ao interpretador configurado 
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
  
      - name: Run Tests
        run: |
          cd tests
          pytest -v
